#!/bin/sh
# Git credential helper for Hatchery drones.
# Install: git config --global credential.helper /usr/local/bin/git-credential-hatchery

case "$1" in
    get)
        TOKEN=$(curl -sf --unix-socket /var/run/github-creds.sock http://localhost/token)
        if [ -z "$TOKEN" ]; then exit 1; fi
        echo "protocol=https"
        echo "host=github.com"
        echo "username=x-access-token"
        echo "password=$TOKEN"
        ;;
esac
